### ISSUE TITLE
Edge case?

### ISSUE THREAD

**Issue by yiheinchai** [yutanagano/tidytcells#4]
An example of a valid HLA type that would fail to match the regex r'^(HLA-)?([A-Za-z/]+\d??)(\*?([\d:]+(G)?(P)?)[LSCAQN]?)?$' is "HLA-DR1*13:01:01". This HLA type is valid because it follows the standard HLA naming conventions, but it would not match the regex because it contains two colons (:) between the digits and the "G" letter, while the regex only allows for one colon. The regex also only allows for one optional letter at the end of the string, but this HLA type has two letters, "G" and "P".

**Comment by yutanagano** [comment]
"HLA-DR1*13:01:01" will match the given regex. The regex allows for multiple digits and colons in succession ([\d:]+). Also, what did you mean by "this HLA type has two letters, "G" and "P"."? The example you gave has neither letter. But also, any valid HLA will never have both letters at the end so that wouldn't be a valid edge case.
